name: Update Index HTML with Secure API

on:
  workflow_dispatch:
    inputs:
      api-key:
        description: 'Google Sheets API Key'
        required: true

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update index.html with secure API key
        env:
          GOOGLE_SHEETS_API_KEY: ${{ github.event.inputs.api-key || secrets.GOOGLE_SHEETS_API_KEY }}
        run: |
          # Ensure the script exists and is readable
          if [ ! -f update_index.sh ]; then
            echo "Creating update script"
            cat > update_index.sh << 'EOF'
          #!/bin/bash
          
          # Read the template index.html
          template=$(cat index.html)
          
          # Replace placeholders with actual values
          updated_html=$(echo "$template" | 
            sed "s/YOUR_GOOGLE_SHEET_ID/$GOOGLE_SHEET_ID/g" |
            sed "s/YOUR_GOOGLE_SHEETS_API_KEY/$GOOGLE_SHEETS_API_KEY/g")
          
          # Write the updated HTML
          echo "$updated_html" > index.html
          EOF
          
            chmod +x update_index.sh
          fi

          # Execute the update script
          GOOGLE_SHEET_ID="${{ secrets.GOOGLE_SHEET_ID }}"
          ./update_index.sh

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add index.html
          git commit -m "Update index.html with secure API configuration"
          git push
